### ISSUE TITLE
This started to occur after the installation of Beta 6 of MacOS Sequoia.  Coincidental???

### ISSUE THREAD

**Issue by j3-signalroom** [j3-signalroom/apache_flink-kickstarter#49]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/aws2-wrap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/__init__.py", line 584, in main
    grc_structure = get_role_credentials(profile)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/__init__.py", line 299, in get_role_credentials
    sso_access_token = retrieve_token(sso_start_url, sso_region, profile_name, refresh_profile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/__init__.py", line 232, in retrieve_token
    return retrieve_token_from_cache(sso_start_url, sso_region, profile_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/__init__.py", line 259, in retrieve_token_from_cache
    token = retrieve_token_from_file(cachefile, sso_start_url, sso_region)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/__init__.py", line 193, in retrieve_token_from_file
    blob = json.load(json_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

**Comment by j3-signalroom** [comment]
I was able to fix the problem by going to the `opt/homebrew/Cellar/aws2-wrap/1.4.0/libexec/lib/python3.12/site-packages/aws2wrap/` folder and running `find . -name '.DS_Store' -type f -delete` from the Terminal.  I believe the problem was being caused by a hidden `.DS_Store` file.
