### ISSUE TITLE
Convert all Python Flink Apps to support Avro Schema instead of JSON. 

### ISSUE THREAD

**Issue by j3-signalroom** [j3-signalroom/apache_flink-kickstarter#500]

**Comment by j3-signalroom** [comment]
```bash
![image](https://github.com/user-attachments/assets/9c14cd3d-ed5e-4224-a25f-c86ea80217e3)```

**Comment by j3-signalroom** [comment]
```bash
ava.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.clients.producer.ProducerConfig
    at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:295)
    at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:322)
    at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:307)
    at org.apache.flink.connector.kafka.sink.FlinkKafkaInternalProducer.<init>(FlinkKafkaInternalProducer.java:60)
    at org.apache.flink.connector.kafka.sink.KafkaWriter.getOrCreateTransactionalProducer(KafkaWriter.java:335)
    at org.apache.flink.connector.kafka.sink.TransactionAborter.abortTransactionOfSubtask(TransactionAborter.java:104)
    at org.apache.flink.connector.kafka.sink.TransactionAborter.abortTransactionsWithPrefix(TransactionAborter.java:82)
    at org.apache.flink.connector.kafka.sink.TransactionAborter.abortLingeringTransactions(TransactionAborter.java:66)
    at org.apache.flink.connector.kafka.sink.KafkaWriter.abortLingeringTransactions(KafkaWriter.java:298)
    at org.apache.flink.connector.kafka.sink.KafkaWriter.<init>(KafkaWriter.java:172)
    at org.apache.flink.connector.kafka.sink.KafkaSink.createWriter(KafkaSink.java:108)
    at org.apache.flink.connector.kafka.sink.KafkaSink.createWriter(KafkaSink.java:55)
    at org.apache.flink.api.connector.sink2.Sink.createWriter(Sink.java:78)
    at org.apache.flink.streaming.runtime.operators.sink.StatefulSinkWriterStateHandler.createWriter(StatefulSinkWriterStateHandler.java:122)
    at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:148)
    at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:147)
    at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:294)
    at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreStateAndGates(StreamTask.java:858)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$restoreInternal$5(StreamTask.java:812)
    at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:812)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:771)
    at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:970)
    at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:939)
    at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:763)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'int com.github.luben.zstd.Zstd.defaultCompressionLevel()' [in thread "Map -> flight_sink: Writer -> flight_sink: Committer (1/1)#0"]
    at org.apache.kafka.common.compress.ZstdCompression.<clinit>(ZstdCompression.java:43)
    at org.apache.kafka.clients.producer.ProducerConfig.<clinit>(ProducerConfig.java:384)
    ... 28 more 
```
