### ISSUE TITLE
`Query schema: [email_address: STRING NOT NULL, departure_time: STRING NOT NULL, departure_airport_code: STRING NOT NULL, arrival_time: STRING NOT NULL, arrival_airport_code: STRING NOT NULL, flight_number: STRING NOT NULL, confirmation_code: STRING NOT NULL, airline: CHAR(6) NOT NULL] Sink schema:  [key: BYTES, val: BYTES]`.

### ISSUE THREAD

**Issue by j3-signalroom** [j3-signalroom/apache_flink-kickstarter#595]
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jeffreyjonathanjennings/j3/code_spaces/apache_flink-kickstarter/python_ccaf/src/kickstarter/avro_flight_consolidator_ccaf_app.py", line 157, in run
    "confirmation_code", "airline").execute_insert(f"`{catalog_name}`.`{database_name}`.`flight_avro`")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffreyjonathanjennings/Library/Caches/pypoetry/virtualenvs/kickstarter-vuhZ_oCq-py3.11/lib/python3.11/site-packages/pyflink/table/table.py", line 1045, in execute_insert
    return TableResult(self._j_table.executeInsert(table_path_or_descriptor, overwrite))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffreyjonathanjennings/Library/Caches/pypoetry/virtualenvs/kickstarter-vuhZ_oCq-py3.11/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jeffreyjonathanjennings/Library/Caches/pypoetry/virtualenvs/kickstarter-vuhZ_oCq-py3.11/lib/python3.11/site-packages/pyflink/util/exceptions.py", line 158, in deco
    raise java_exception
pyflink.util.exceptions.TableException: org.apache.flink.table.api.TableException: Failed to execute sql
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1060)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:876)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1107)
        at org.apache.flink.table.api.internal.TablePipelineImpl.execute(TablePipelineImpl.java:59)
        at org.apache.flink.table.api.Table.executeInsert(Table.java:1074)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
        at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
        at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
        at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.confluent.flink.plugin.ConfluentFlinkException: Statement 'table-api-2024-12-20-225612-8945299c-b4a5-4d5c-80d3-ec2d90aef49d-api' failed.
Reason: Column types of query result and sink for 'flink_kickstarter-env.flink_kickstarter-kafka_cluster.flight_avro' do not match.
Cause: Different number of columns.

Query schema: [email_address: STRING NOT NULL, departure_time: STRING NOT NULL, departure_airport_code: STRING NOT NULL, arrival_time: STRING NOT NULL, arrival_airport_code: STRING NOT NULL, flight_number: STRING NOT NULL, confirmation_code: STRING NOT NULL, airline: CHAR(6) NOT NULL]
Sink schema:  [key: BYTES, val: BYTES]
        at io.confluent.flink.plugin.internal.DefaultPluginContext.lambda$statementStatusCondition$9(DefaultPluginContext.java:499)
        at io.confluent.flink.plugin.internal.DefaultPluginContext.waitForCondition(DefaultPluginContext.java:560)
        at io.confluent.flink.plugin.internal.DefaultPluginContext.waitForStatementStatus(DefaultPluginContext.java:436)
        at io.confluent.flink.plugin.internal.DefaultPluginContext.submitStatement(DefaultPluginContext.java:391)
        at io.confluent.flink.plugin.internal.DefaultPluginContext.querySuccess(DefaultPluginContext.java:277)
        at io.confluent.flink.plugin.internal.ConfluentExecutor.executeModify(ConfluentExecutor.java:132)
        at io.confluent.flink.plugin.internal.ConfluentExecutor.executeAsync(ConfluentExecutor.java:89)
        at org.apache.flink.table.executor.python.ChainingOptimizingExecutor.executeAsync(ChainingOptimizingExecutor.java:88)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1032)
        ... 13 more
```

**Comment by j3-signalroom** [comment]
So the problem is the Query schema does not match the Sink schema.  Why?  What do I need to do to match them up?

**Comment by j3-signalroom** [comment]
Since, I already created the table in Terraform, it will by default have a schema defined for the table as `key BYTES`, `val BYTES`.  So, to resolved the problem remove the pre-creation of the Topic in Terraform and only do it in code in the various Flink Apps that produce to the Topic.
